name: Service1 Deploy

permissions:
  id-token: write
  contents: write
  pull-requests: write
  packages: read
on:
  push:
    branches: [ main ]
    paths:
      - "backends/apis/service1/**"
      - ".github/workflows/service1.yml"
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage to deploy to - for example, "dev" or "prod"'
        required: true
        default: 'dev'
jobs:
  lower-env-deploy:
    name: Deploy Lower Environment
    runs-on: ubuntu-latest
    concurrency:
      group: svc1-lower-env-deploy
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Fake deploy
        run: echo "HI MOM"
  release-please:
    name: Release Please
    needs:
      - lower-env-deploy
    concurrency:
      group: svc1-release-please
      cancel-in-progress: true
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs['backends/apis/service1--release_created'] }}
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: backends/apis/service1/release-please-config.json
      - name: Echo JSON Output
        run: echo '${{ toJson(steps.release.outputs) }}'
  prod-deploy:
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.release-created }}
    concurrency:
      group: svc1-prod-deploy
      cancel-in-progress: true
    environment: prod
    name: Deploy Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fake deploy
        run: echo "HI MOM"
